kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter_opts:
    default_lang: javascript
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-optional-front-matter
  - jekyll-default-layout